name = input('What is  your name? ')
age = input('How old are you? ')
goal = input('What is your goal in tech? ')
favorite_thing = input('What is your favorite thing to do? ')

print(f'\n=== YOUR PROFILE===')
print(f'Name: {name}')
print(f'Age: {age}')
print(f'Goal: {goal}')
print(f'Favorite thing: {favorite_thing}')